mongodb:
  uri: "mongodb://localhost:27017"
  database: "smp"

lastfm:
  enabled: false
  api-key: ""

protection:
  spawn:
    enabled: true
    world: "world"
    radius: 10 # Set to 0 for none
  disable-tnt:
    enabled: true
    worlds: # Name of folder
      - "world"
  sign:
    prevent-edit-others: true # Disable editing signs that arent yours


chat:
  enabled: true
  format: "%luckperms_prefix%<player> <gray>(<red>@%discordsrv_user_name%<gray>)<white>:<reset> <message>"

# format: https://docs.advntr.dev/minimessage/format.html
# plugin placeholders:
# <spawn-protection> if the player is within spawn radius

scoreboard:
  enabled: true
  title: "<dark_red><b>SMP" # no placeholder support
  lines:
    - "<gray><st>                          <reset> "
    - "<red>Online<gray>: <reset><players>"
    - "<red>Protection<gray>: <reset><spawn-protection>"
    - "<reset>"
    - "<gray>play.goodasssub.com"
    - "<gray><st>                          <reset> "
