mongodb:
  uri: 'mongodb://localhost:27017'
  database: 'smp'

lastfm:
  enabled: false
  api-key: ''

spawn:
  protection:
    world: world
    radius: 20 # Set to 0 for none
    message: "&cYou cannot do this in spawn protection!" # message sent when cancelling an event

chat-format:
  enabled: true
  player-message: "placeholder"
  join-message: "placeholder"
  leave-message: "placeholder"

disable-tnt:
  enabled: true
  message: ""
  worlds: # Name of folder
    - "world"

# placeholders
# {spawnprotection}: equals true if player has spawn protection

scoreboard:
  enabled: true
  title: "&c&lGood Ass Sub"
  lines:
    - "&7&m                    "
    - "&cOnline&7: &f%online-players%"
    - '&cProtection&7: &f{spawnprotection}!'
    - ""
    - "&7play.goodasssub.com" # eventually just have play holder that shows server ip instead
    - "&7&m                    "
