spawn:
  protection:
    radius: 10 # Set to 0 for none
    message: "&cYou cannot do this in spawn protection!" # message sent when cancelling an event

chat-format:
  enabled: true
  player-message: "placeholder"
  join-message: "placeholder"
  leave-message: "placeholder"

disable-tnt:
  enabled: true
  message: ""
  worlds: # Name of folder
    - "world"

# placeholders
# {spawnprotection}: equals true if player has spawn protection

scoreboard:
  enabled: true
  title: "&cTitle &7| &fServer"
  lines:
    - "&7&m                    "
    - "&cOnline: &f%onlineplayers%"
    #    - '&c{spawnprotection}!' Not implemented
    - ""
    - "&7play.goodasssub.com"
    - "&7&m                    "
